#!/bin/bash
# Just generates the documentations

###########################################################

STATEMENTS_LIST_FILE="doc/all-statements.ds"
COMMANDS_TREE_FILE="doc/commands-tree.txt"
COMMANDS_OVERVIEW_FILE="doc/commands.md"

###########################################################
# Statements

echo "# Generated by the gendoc.sh and list-statements.pl" > $STATEMENTS_LIST_FILE
perl list-statements.pl >> $STATEMENTS_LIST_FILE

echo "Statements done!"

###########################################################
# Commands tree

echo "Note: This file was generated by the gendoc.sh and list-commands.pl" > $COMMANDS_TREE_FILE
perl list-commands.pl >> $COMMANDS_TREE_FILE

echo "Commands tree done!"

###########################################################
# Commands overview

echo -e "# The commands overview\n" \
        "This file contains overview of the supported disketo script commands, their parameters, arguments and values.\n" \
        "_Note: This file was generated by the \`gendoc.sh\`._\n" \
	"# The \"root\" commands\n" \
	"Each statement has to start with any of this commands:\n\n" \
      	> $COMMANDS_OVERVIEW_FILE

echo -e "BEGIN { unshift @INC, '.'; }\n" \
        "use Disketo_Instruction_Set;\n" \
	"print(join(' ',map{'['.\$_->{'name'}.'](#'.\$_->{'ID'}.')'}values%{Disketo_Instruction_Set::commands()}));\n" \
	| perl >> $COMMANDS_OVERVIEW_FILE

echo -e "\n\n" \
	"After that, continue with its declared parameter's values or (sub)commands.\n" \
      	>> $COMMANDS_OVERVIEW_FILE


echo -e "BEGIN { unshift @INC, '.'; }\n" \
        "use Disketo_Help;\n" \
        "Disketo_Help::print_list_of_commands_in_markdown();\n"\
	| perl >> $COMMANDS_OVERVIEW_FILE

echo "Commands overview done!"
###########################################################

